{% set name = "opentelemetry-exporter-otlp" %}
{% set version = "1.34.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_exporter_otlp-{{ version }}.tar.gz
  sha256: d23df4fc22e0a863db2b2117c5a5780d5fa3bbeb65fdce9848d1f98fc3ace4cd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - opentelemetry-exporter-otlp-proto-grpc ==1.34.0
    - opentelemetry-exporter-otlp-proto-http ==1.34.0

test:
  imports:
    - opentelemetry
    - opentelemetry.exporter.otlp
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/main/exporter/opentelemetry-exporter-otlp
  summary: OpenTelemetry Collector Exporters
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
    - rxm7706
    - conda-forge/opentelemetry-api
    - conda-forge/opentelemetry-proto
    - conda-forge/opentelemetry-sdk
    - conda-forge/opentelemetry-exporter-otlp-proto-common
    - conda-forge/opentelemetry-exporter-otlp-proto-grpc
    - conda-forge/opentelemetry-exporter-otlp-proto-http
